//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIUB.Shop_Management.Default
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Brand
    {
        public Product_Brand()
        {
            this.Products = new HashSet<Product>();
            this.Purchases = new HashSet<Purchase>();
        }
    
        public string Product_Type { get; set; }
        public string Brand { get; set; }
        public string Name { get; set; }
        public string ProductId { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Purchase> Purchases { get; set; }
    }
}
